### ISSUE TITLE
expose highlight group for `auto_jump = true` 

### ISSUE THREAD

**Issue by gennaro-tedesco** [hedyhli/outline.nvim#27]
Thank you very much for the great work you have been doing to revive symbols-outline: this plugin is awesome!

Is it possible to customise the highlight group of the code reference that one gets using (see README)

```lua
outline_window = {
  auto_jump = true,
},
```
namely when setting the above option, scrolling through the outline list of methods highlights the corresponding piece of code in the main buffer? If I understand correctly such highlight is currently defaulting to the `Visual` highlight group - would it be possible to expose it to the user to customise it? The reason is that one may like a "less invasive" highlight group to show when scrolling fast through the outline list (and in many neovim themes the visual highlight group stands out very much).

**Comment by hedyhli** [comment]
I agree with the reasoning. The highlight group as well as the duration of the highlight should also be customizable for a better experience.

I'm currently working on #23, will get to this as soon as that one's shipped 👍

**Comment by hedyhli** [comment]
https://github.com/hedyhli/outline.nvim/assets/50042066/cb453a8e-eccf-4b8a-943f-725ef31839ff

Let me know if you encounter any issues!

**Comment by gennaro-tedesco** [comment]
Thank for working on it so fast! 

Isn't the configuration option available via `outline_window.winhl`? If I set it up via command (like in your example) it works perfectly, if I specify it as an option it takes no effect (thus I suspect you didn't add it to the setup options?).

**Comment by hedyhli** [comment]
You can't use winhl for this because this highlight group is for code window and not for outline window :)

**Comment by gennaro-tedesco** [comment]
Aaaaah, of course! I will set it in the general options though, thank you!
