### ISSUE TITLE
Feature Request: Sidebar live filter

### ISSUE THREAD

**Issue by kevintraver** [hedyhli/outline.nvim#31]
Feature Request: Ability to filter the list of symbols in the sidebar view.

**Comment by hedyhli** [comment]
Hi, can you describe in more detail how this feature works? Is it a 'live' filtering, by fzf? by kind?

Note that at the moment we do have the [`symbols.filter`](https://github.com/hedyhli/outline.nvim?tab=readme-ov-file#symbols-table) config option, just that you can't do it live on the sidebar.

**Comment by kevintraver** [comment]
Yes, It would be a live filter, by symbol name. As you type, it would narrow down the list of symbols in the sidebar.

Could maybe be similar to how how [neo-tree](https://github.com/nvim-neo-tree/neo-tree.nvim) does `fuzzy_finder`
