### ISSUE TITLE
Feature Request: Recognise shorthand React fragments as "Fragment" in outlines

### ISSUE THREAD

**Issue by gambonny** [hedyhli/outline.nvim#35]
<img width="1554" alt="Screenshot 2023-11-22 at 18 31 51" src="https://github.com/hedyhli/outline.nvim/assets/88061915/36e38d03-4eff-4c60-a357-e71c71e9655c">

---

When using outline.nvim to view the structure of React components, shorthand React fragments (`<>...</>`) are currently labeled as `unknown` in the outline view. This can be confusing and does not accurately reflect the structure of the component.

### Feature Request
I propose an enhancement to the outline detection logic to identify shorthand React fragments and label them as "Fragment" in the outline. This would improve the clarity and usefulness of the outline view for React developers who use this syntax.

**Comment by hedyhli** [comment]
Actually this looks like a bug, will get to it soon. Thanks!

**Comment by hedyhli** [comment]
This was due to tree-sitter/tree-sitter-javascript#227. It's fixed now, let me know if you're still having issues.

**Comment by gambonny** [comment]
@hedyhli it's working. Thanks a lot 👍.
