### ISSUE TITLE
Memory leak on cursor move event?

### ISSUE THREAD

**Issue by Djedouas** [hedyhli/outline.nvim#38]
When moving cursor, line to line, I can see my RAM going up and up.

Until Ubuntu kills neovim when 100% RAM is used.

When I close the outline, the memory is freed.

[Download demo video](https://send.volpes.fr/download/7b6f5d8051902099/#UupEf4fskUllPvT2Q13ufQ)

**Comment by hedyhli** [comment]
I will have a look into this, for now you can set `outline_items.auto_update_events.follow = {'CursorHold'}` the memory usage should be better.

**Comment by hedyhli** [comment]
It turned out to be a one-liner fix for which the problem arose from inappropriate function naming from symbols-outline.nvim. Should be fixed now, but do let me know if you're still seeing this issue.

**Comment by Djedouas** [comment]
Perfect! Everything is fine now!

Thanks 😉
