### ISSUE TITLE
Feature request: tags support

### ISSUE THREAD

**Issue by ShaolunWang** [hedyhli/outline.nvim#40]
Love the plugin! I was wondering would it be possible to have tagfile support in the future? On large codebase lsp may not work properly and tags can be used as a fallback method, especially for c/c++ development.

**Comment by hedyhli** [comment]
I am generally in favor of this. It could be a separate provider that checks for the tagfile.

However, I don't have much experience with the format of tagfile, so this would have to be implemented by someone else through a PR.

**Comment by underwoodtan** [comment]
Universal-ctags support JSON output format basically enough information, so it's easy to write a simple provider, but ctags don't have the consistency that LSP has, so it's hard to handle conner-cases，and harder to support muti languages。
I have impl a sample systemverilog provider based on ctags. I am not familiar with lua,so it's a bit ugly。Do you wish to take over it?
