### ISSUE TITLE
has_provider() is not available in the public API

### ISSUE THREAD

**Issue by Khyonie** [hedyhli/outline.nvim#48]
The "Lua API" section of the documentation says that the function `has_provider()` is available, but since that function is inside [providers/init.lua](https://github.com/hedyhli/outline.nvim/blob/main/lua/outline/providers/init.lua) it isn't. I'm pretty terrible with lua, but my current workaround is doing `require("outline.providers").has_outline()`.

Either add that `has_provider()` is inside the "providers" module to the documentation or make it accessible in the base "outline" module? 

(I'd be happy to submit a quick PR, though I don't trust any lua I write, hahaha)

**Comment by hedyhli** [comment]
Thanks for bringing it up, I've added it to the outline module.
