### ISSUE TITLE
E492: Not an editor command: Outline

### ISSUE THREAD

**Issue by natemurthy** [hedyhli/outline.nvim#55]
I have installed on macOS laptop:
```
NVIM v0.8.3
LuaJIT 2.1.0-beta3
```
with CoC. You can see below from my `:PlugStatus` that neovim can detect the `outline.vim` plug-in:

<img width="241" alt="Screenshot 2024-03-09 at 4 01 34 PM" src="https://github.com/hedyhli/outline.nvim/assets/1788878/2dcbbca1-8471-409d-b05e-06dba5c56dc3">

But when I invoke `:Outline` I observer the `E492: Not an editor command: Outline` error. 

Please advise on how best to resolve 🙂 (there's probably some configuration step I'm missing)

**Comment by hedyhli** [comment]
Hi! You need to call the setup function somewhere in your config.

https://github.com/hedyhli/outline.nvim?tab=readme-ov-file#setup

Please reopen if you're still encountering the issue.
