### ISSUE TITLE
Mouse support

### ISSUE THREAD

**Issue by sodle-splunk** [hedyhli/outline.nvim#56]
Is there a way to configure this so that clicking or double-clicking a symbol in the outline will jump to it? I'm using LunarVim with `mouse = "a"`, and currently the mouse is only able to select the text of the outline.

**Comment by hedyhli** [comment]
As of now you can add `<LeftRelease>` to your keymap for `goto_location`:
```lua
keymaps = {
  -- ...
  goto_location = {"<CR>", "<LeftRelease>"},
  -- ...
}
```
This lets you jump to the symbol location on single mouse clicks. Does that solve your issue?

https://github.com/hedyhli/outline.nvim/assets/50042066/07d5416c-b19d-4923-98e7-b0d2a2e0ad12

**Comment by sodle-splunk** [comment]
Yep, that works! Thanks for the tip!
