### ISSUE TITLE
Feature request: allow setting the window width

### ISSUE THREAD

**Issue by yuriescl** [hedyhli/outline.nvim#59]
When I run `:Outline` it opens a window but it's too small, I'd like to be able to set how many columns I want for the Outline window.

**Comment by hedyhli** [comment]
Hi, please take a look at the config section of the docs:
https://github.com/hedyhli/outline.nvim?tab=readme-ov-file#default-options
```lua
{
  outline_window = {
    -- ...
    -- Percentage or integer of columns
    width = 25, 
    -- Whether width is relative to the total width of nvim
    -- When relative_width = true, this means take 25% of the total
    -- screen width for outline window.
    relative_width = true,
    -- ...
}
```
