### ISSUE TITLE
question: make go project show the same outline as c++ project.

### ISSUE THREAD

**Issue by ericwq** [hedyhli/outline.nvim#79]
The following is the outline of my go project. You will immediately notice that most method name cant' be showed easily, because struct name take most space.
<img width="335" alt="Screenshot 2024-07-02 at 19 38 44" src="https://github.com/hedyhli/outline.nvim/assets/1501146/ced78ba7-7dca-4c26-8b89-85e1adb55f59">

The following is the outline of some c++ project (using the same outline plugin). It's obvious that all the methods name can be showed easily. My question is how to config my go project to show outline like c++ project? 

After search full doc and issue list, I got nothing but go for help.
<img width="332" alt="Screenshot 2024-07-02 at 19 38 28" src="https://github.com/hedyhli/outline.nvim/assets/1501146/9277bfd5-6c1a-4b38-8ac2-b7f4dfd13a82">

**Comment by hedyhli** [comment]
Unfortunately, this is what the LSP provides and there's not much we can do on our side to help with it.

The methods I have in my Go projects, where I use gopls also show up as function with the pointer receivers prefixed. In Go, methods are defined at the same level as the structs, whereas in C++ it's defined "inside" a class.

Again, I understand that it's more readable if Go methods also show up nested, with the pointer receiver prefixes removed and I experience pain too, but that's what the LSP provides outline.nvim simply displays what the LSP gives it.
