### ISSUE TITLE
How to configure outline.nvim for Quarto?

### ISSUE THREAD

**Issue by marcocamilo** [hedyhli/outline.nvim#80]
I love this plugin and would like to know how can I configure it for .qmd files. Quarto files are a special type of markdown file which allow for mixing markdown with programming languages (Python, Julia, R, etc.)

When I run outline.nvim in a .qmd file, I get:

```Messages: (outline) No response from provider when requesting symbols!```

Outline works with markdown files, so how can I make it work with this type of file (which is essentially also markdown)?

**Comment by hedyhli** [comment]
Please take a look at the list of default options in the docs, notice:

```lua
  providers = {
    -- ...
    markdown = {
      -- List of supported ft's to use the markdown provider
      filetypes = {'markdown'},
    },
  },
```

**Comment by marcocamilo** [comment]
Thank you for the reference. However, I configured it this way:

```
    providers = {
      markdown = {
        filetypes = { "markdown", "quarto" },
      },
    },
```

but still get: `Messages: (outline) No response from provider when requesting symbols!`. Am I missing something?

**Comment by hedyhli** [comment]
Try running `:OutlineStatus` in a quarto buffer, it tells you which provider it ends up using.

If it doesn't show the markdown provider, you should update `providers.priority` so that `markdown` is the first provider tried.

**Comment by marcocamilo** [comment]
Hi, sorry for the really delayed response. I finally tried it and it worked! Here's the config right now:

```
providers = {
	priority = { "markdown", "lsp", "coc", "norg" },
	markdown = {
		filetypes = { "markdown", "quarto" },
	},
},
```
