### ISSUE TITLE
how change height

### ISSUE THREAD

**Issue by sineptic** [hedyhli/outline.nvim#83]
I want change height for preview window. I found only how change height, in documentation(in nvim) search for "height" displays 0 matches.

**Comment by oskarrrrrrr** [comment]
You can use `min_height` setting like this:
```
preview_window = {
    min_height=100
}
```
Height will automatically get truncated so that the preview window fits inside nvim.

**Comment by sineptic** [comment]
but can I make it 70% or 80% for example?

**Comment by oskarrrrrrr** [comment]
Not right now, but it could be added. There already is an equivalent setting for width.

**Comment by oskarrrrrrr** [comment]
I don't know why, I added a PR to add those settings for height: #84

**Comment by sineptic** [comment]
thank you!
