### ISSUE TITLE
How to set outline window to auto close after code window closed?

### ISSUE THREAD

**Issue by mengq627** [hedyhli/outline.nvim#86]
when I open outline window and code window, if I close code window by `:wq`, I need to close outline window by `:q` again.
I have not seen related configuration in doc.

**Comment by oskarrrrrrr** [comment]
I think it's not possible right now, but I would like this feature as well :)

**Comment by hedyhli** [comment]
I recommend having a keybinding or some other way so you can easily `:qa` or `:wqa`. Personally I use a keybinding for this and would use it whenever I want to exit neovim, regardless of how many windows are open.

**Comment by MengQ0627** [comment]
> I recommend having a keybinding or some other way so you can easily `:qa` or `:wqa`. Personally I use a keybinding for this and would use it whenever I want to exit neovim, regardless of how many windows are open.

That's good, it is useful.
However, I have not set plugin which can open&edit multiple file at same time, I don't know what to do when closing one of multiple files
, is this method still valid?

**Comment by hedyhli** [comment]
qa/wqs closes multiple buffers and windows. And you can use to close both the outline and the code window, or if the outline isn't open at all.

An autocmd can also be used that closes neo I'm when a window is closed and the outline is the last one remaining, so I wouldn't really consider this something outline.nvim needs to support.

**Comment by niderhoff** [comment]
I am using this autocmd and it seems to work:

```lua
vim.api.nvim_create_autocmd("BufEnter", {
    callback = function()
        if vim.bo.filetype == "Outline" and vim.fn.winnr('$') == 1 then
            vim.cmd("q")
        end
    end,
})
```

**Comment by mengq627** [comment]
> I am using this autocmd and it seems to work. When entering a buffer is triggered it checks that the buffer filetype is Outline and if we are in the last remaining window, it will close neovim.
> 
> ```lua
> vim.api.nvim_create_autocmd("BufEnter", {
>     callback = function()
>         if vim.bo.filetype == "Outline" and vim.fn.winnr('$') == 1 then
>             vim.cmd("q")
>         end
>     end,
> })
> ```

It's so great, help me a lot.

**Comment by dmtrKovalenko** [comment]
I tried the solution and it doesn't work for my setup because of a lot of hidden windows here is the much more reliable appraoch

```lua
   vim.api.nvim_create_autocmd("BufEnter", {
        callback = function()
          local function count_normal_windows()
            local count = 0
            for _, win in ipairs(vim.api.nvim_list_wins()) do
              local config = vim.api.nvim_win_get_config(win)
              if config.relative == "" then -- Non-floating windows
                count = count + 1
              end
            end
            return count
          end

          if vim.bo.filetype == "Outline" and count_normal_windows() == 1 then
            vim.cmd "q"
          end
        end,
      })
```
