### ISSUE TITLE
Folds on html tags

### ISSUE THREAD

**Issue by gabs712** [hedyhli/outline.nvim#97]
## Description
Currently the way that symbols are displayed on html filetypes are as follows:
![Screenshot_20241015_133859](https://github.com/user-attachments/assets/bdcb2e03-0f92-4da5-938c-1c8234ed7573)
The highlights still provide a notion of depth but they're not quite as good as the folds that are displayed
in most of programming languages.

Would be cool to have something like this instead:
![Screenshot_20241015_135913](https://github.com/user-attachments/assets/cd62159d-53ee-4b7b-bef5-49eed158606f)

**Comment by hedyhli** [comment]
The symbols themselves and their hierarchy is completely dependent on the LSP used. It seems that the HTML LSP displays them this way, but I have used another LSP that supports correct hierarchy.
