### ISSUE TITLE
Symbol sorting

### ISSUE THREAD

**Issue by zalegrala** [hedyhli/outline.nvim#98]
## Description

Occasionally a file is not well ordered, but I would like the symbols to be sorted and uniform.  Consider the following.

![image](https://github.com/user-attachments/assets/2221fd9b-d203-42c3-ae28-06f32348dde4)

It might be nice to nest all of the instance methods under the type as if it were ordered well in the file.  Additionally, and files with lots of types and methods, the names are sometimes hard to know if the file does not have the types in alphabetical order.  A method to sort the `outline` would be nice.

**Comment by hedyhli** [comment]
This might be a little involved to implement and isn't something I would consider within scope for the outline plugin, whose purpose is to make navigation easier by reflecting the symbols in a file in order which they are defined.

I can see how this can be useful though, so I will merge this request with Telescope support where we can have the symbols show in a sorted order: #17
